backend:
  nom: git-gateway
  branch: master # Branche à mettre à jour (facultatif ; par défaut, master)
dossier_média: "statique/téléchargements"
dossier_public: "/téléchargements"
collections:
  - nom: "articles"
    étiquette: "article"
    dossier: "articles"
    créer: vrai
    slug: "{{slug}}"
    champs:
      - { étiquette: "Titre", nom: "titre", widget: "chaîne " }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown " }
